apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ykantoni/verda-k8s-infra.git
    targetRevision: HEAD
    path: gateway-routes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
